[package]
name = "synacor-challenge-rs"
version = "0.1.0"
authors = ["Gabor Pihaj <gabor.pihaj@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
